### ISSUE TITLE
How do I install this game?

### ISSUE THREAD

**Issue by pheis** [rottabonus/seppo_the_sheepdog#1]
I wanna get to play as Seppo the sheep dog. How Do I get to do that?

**Comment by rottabonus** [comment]
I'll upload it to ithc.io when its ready and update the readme.

**Comment by rottabonus** [comment]
closed by accident, will close it when the game is available babes

**Comment by rottabonus** [comment]
@pheis you should be able to play as Seppo now here: https://rottabonus.itch.io/seppo-the-sheepdog
